// GENERATED by `dart run serious_python:gen_version_tables` from python-build's
// manifest.json (release 20260712). Do not edit by hand — edit python-build's
// manifest.json, cut a release, bump `pythonReleaseDate`, and regenerate.

const pythonVersionEnvironmentVariable = "SERIOUS_PYTHON_VERSION";
const pythonFullVersionEnvironmentVariable = "SERIOUS_PYTHON_FULL_VERSION";
const pythonDistReleaseEnvironmentVariable = "SERIOUS_PYTHON_DIST_RELEASE";
const pythonBuildDateEnvironmentVariable = "SERIOUS_PYTHON_BUILD_DATE";
const pyodideVersionEnvironmentVariable = "SERIOUS_PYTHON_PYODIDE_VERSION";
const dartBridgeVersionEnvironmentVariable = "DART_BRIDGE_VERSION";

/// python-build release the bundled runtimes come from (YYYYMMDD).
const pythonReleaseDate = "20260712";
const dartBridgeVersion = "1.5.0";
const defaultPythonVersion = "3.14";

class PythonRelease {
  const PythonRelease({
    required this.standaloneVersion,
    required this.standaloneReleaseDate,
    required this.pyodideVersion,
    required this.pyodidePlatformTag,
    required this.androidAbis,
    required this.prerelease,
  });

  final String standaloneVersion;
  final String standaloneReleaseDate;
  final String pyodideVersion;
  final String pyodidePlatformTag;

  /// Android ABIs python-build publishes distributions for
  /// this minor (per the manifest's per-minor `android_abis`).
  final List<String> androidAbis;

  final bool prerelease;
}

const pythonReleases = <String, PythonRelease>{
  "3.12": PythonRelease(
    standaloneVersion: "3.12.13",
    standaloneReleaseDate: "20260623",
    pyodideVersion: "0.27.7",
    pyodidePlatformTag: "pyodide-2024.0-wasm32",
    androidAbis: ["arm64-v8a", "x86_64", "armeabi-v7a"],
    prerelease: false,
  ),
  "3.13": PythonRelease(
    standaloneVersion: "3.13.14",
    standaloneReleaseDate: "20260623",
    pyodideVersion: "0.29.4",
    pyodidePlatformTag: "pyemscripten-2025.0-wasm32",
    androidAbis: ["arm64-v8a", "x86_64", "armeabi-v7a"],
    prerelease: false,
  ),
  "3.14": PythonRelease(
    standaloneVersion: "3.14.6",
    standaloneReleaseDate: "20260623",
    pyodideVersion: "314.0.2",
    pyodidePlatformTag: "pyemscripten-2026.0-wasm32",
    androidAbis: ["arm64-v8a", "x86_64", "armeabi-v7a"],
    prerelease: false,
  ),
};
